name: csv-pdf 

services:
  app:
    image: schweigenderflugel/cvs-to-pdf:0.1
    restart: on-failure
    deploy:
      replicas: 3
    networks:
      - app_network

  nginx:
    container_name: nginx
    image: nginx:1.27-alpine3.20
    restart: unless-stopped
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-certs/nginx-selfsigned.key:/nginx-certs/nginx-selfsigned.key:ro
      - ./nginx-certs/nginx-selfsigned.crt:/nginx-certs/nginx-selfsigned.crt:ro
    ports:
      - "8080:80"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
    name: csv-pdf_default