apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.appName }}
  name: {{ .Values.serviceName }}
spec:
  ports:
  - name: 80-80
    port: {{ .Values.sourcePort }}
    protocol: TCP
    targetPort: 80
  selector:
    app: csv-to-pdf-svc
  type: ClusterIP
  # type: NodePort # For AWS LoadBalancer control
