# Remove current "certs" directory
rm -rf certs

# Create directory for autogenerated certs
mkdir certs

# Move into "certs" directory
cd certs

# Autogenerate certs
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout nginx-selfsigned.key -out nginx-selfsigned.crt