name: Security Analysis

on:
  pull_request:
    branches: 
      - main
    types: [opened, synchronize, reopened]

permissions:
  security-events: write
  actions: read
  contents: read
  packages: write
  pull-requests: write

jobs:
  rule-check:
    runs-on: ubuntu-22.04
    steps: 
      - name: Checkout
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
        with:
          fetch-depth: 0
      
      - name: Bearer
        uses: bearer/bearer-action@828eeb928ce2f4a7ca5ed57fb8b59508cb8c79bc
        with:
          format: sarif
          output: results.sarif
          only-rule: javascript_express_cookie_missing_http_only,javascript_express_cross_site_scripting,javascript_lang_sql_injection
          exit-code: 0

      - name: Upload SARIF file
        if: always()
        uses: github/codeql-action/upload-sarif@3f0edd48f812cd4456637edc0d7827a0a89d87b9
        with:
          sarif_file: results.sarif
  
  image-scan:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@e3d2460bbb42d7710191569f88069044cfb9d8cf
        with:
          fetch-depth: 0

      - name: Log into registry docker.io
        uses: docker/login-action@b161681273e9a62136351194d2df85acea10488f
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          push: false
          tags: lawcase-server:${{ github.sha }}

      - name: Docker Scout
        uses: docker/scout-action@0133ff88fe16d4a412dc4827a8fccbccb6b583e0
        with:
          command: quickview,cves
          only-severities: critical,high
          sarif-file: scout-report.sarif
          write-comment: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1
        if: always()
        with:
          name: scout-results
          path: scout-report.sarif
          retention-days: 14